name: TurtleSim
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: jadedResearcher <gtg287y@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  AudioLib:
    git: git://github.com/FarragoFiction/AudioLib.git
  DollLibCorrect:
    git: git://github.com/FarragoFiction/DollLibCorrect.git

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
  pedantic: ^1.0.0
